### ISSUE TITLE
交互式地输入信息

### ISSUE THREAD

**Issue by sakurafisch** [lightyears1998/gzhu-schedule-export#1]
如果通过交互的方式，让用户从键盘中输入学号、密码、学年等信息，可以很方便地发布成exe文件

**Comment by lightyears1998** [comment]
考虑在下一个版本中加入交互模式吧。

发布为exe我觉得并不必要，毕竟这只是一个小脚本●ω●，如果运行要带上巨量的库就太累赘了。

**Comment by lightyears1998** [comment]
交互式信息输入要处理问题太多了QAQ。另外其实脚本的异常处理对终端用户并不是很友好，包装起来之后也是可能会吓到人。还是就此作罢吧。 

其实会用这个脚本的人应该多数懂得编程吧。

这个 f9258d99ea0d56ef88c3d307225995661b8a6319 检查用户是否输入信息，如果用户没有输入信息，则提示他们先输入信息后再运行脚本。
